// MET values from the 2024 Adult Compendium of Physical Activities (Herrmann SD et al.,
// J Sport Health Sci 2024, PMID 38242596; https://pacompendium.com). Code = Compendium activity code.
// Calories ≈ MET × body weight (kg) × hours.

export type Activity = { id: string; label: string; met: number; code: string; group: string };

export const ACTIVITIES: Activity[] = [
  { id: "walk-slow", group: "Walking", label: "Walking, 2.5 mph (4 km/h)", met: 3.0, code: "17170" },
  { id: "walk-moderate", group: "Walking", label: "Walking, 2.8–3.4 mph (4.5–5.5 km/h)", met: 3.8, code: "17190" },
  { id: "walk-brisk", group: "Walking", label: "Walking, brisk, 3.5–3.9 mph (5.6–6.3 km/h)", met: 4.8, code: "17200" },
  { id: "walk-very-brisk", group: "Walking", label: "Walking, very brisk, 4.0–4.4 mph (6.4–7.1 km/h)", met: 5.5, code: "17220" },
  { id: "walk-dog", group: "Walking", label: "Walking the dog", met: 3.0, code: "17165" },
  { id: "hiking", group: "Walking", label: "Hiking, cross country", met: 6.0, code: "17080" },
  { id: "stairs", group: "Walking", label: "Stair climbing, general", met: 6.8, code: "17131" },
  { id: "jog", group: "Running", label: "Jogging, general", met: 7.5, code: "12020" },
  { id: "run-5", group: "Running", label: "Running, 5 mph (8 km/h, 12 min/mile)", met: 8.5, code: "12030" },
  { id: "run-6", group: "Running", label: "Running, 6 mph (9.7 km/h, 10 min/mile)", met: 9.3, code: "12050" },
  { id: "run-7", group: "Running", label: "Running, 7 mph (11.3 km/h, 8.5 min/mile)", met: 11.0, code: "12070" },
  { id: "run-8", group: "Running", label: "Running, 8 mph (12.9 km/h, 7.5 min/mile)", met: 12.0, code: "12090" },
  { id: "run-9", group: "Running", label: "Running, 9 mph (14.5 km/h, 6.5 min/mile)", met: 13.0, code: "12110" },
  { id: "run-10", group: "Running", label: "Running, 10 mph (16 km/h, 6 min/mile)", met: 14.8, code: "12120" },
  { id: "bike-leisure", group: "Cycling", label: "Cycling, under 10 mph (16 km/h), leisure", met: 4.0, code: "01010" },
  { id: "bike-light", group: "Cycling", label: "Cycling, 10–11.9 mph (16–19 km/h), light effort", met: 6.8, code: "01020" },
  { id: "bike-moderate", group: "Cycling", label: "Cycling, 12–13.9 mph (19–22 km/h), moderate effort", met: 8.0, code: "01030" },
  { id: "bike-vigorous", group: "Cycling", label: "Cycling, 14–15.9 mph (22–26 km/h), vigorous effort", met: 10.0, code: "01040" },
  { id: "bike-stationary", group: "Cycling", label: "Stationary bike, general", met: 6.8, code: "01200" },
  { id: "spin", group: "Cycling", label: "Spin class", met: 9.0, code: "01270" },
  { id: "weights", group: "Gym", label: "Weight training, 8–15 reps", met: 3.5, code: "02054" },
  { id: "weights-vigorous", group: "Gym", label: "Weight lifting, vigorous (power lifting, body building)", met: 6.0, code: "02050" },
  { id: "circuit", group: "Gym", label: "Circuit training, moderate effort", met: 5.0, code: "02035" },
  { id: "elliptical", group: "Gym", label: "Elliptical, moderate effort", met: 5.0, code: "02048" },
  { id: "elliptical-vigorous", group: "Gym", label: "Elliptical, vigorous effort", met: 9.0, code: "02049" },
  { id: "rowing", group: "Gym", label: "Rowing machine, moderate effort", met: 5.0, code: "02071" },
  { id: "rowing-vigorous", group: "Gym", label: "Rowing machine, vigorous effort", met: 7.3, code: "02070" },
  { id: "calisthenics", group: "Gym", label: "Bodyweight exercises (push-ups, lunges), moderate", met: 3.8, code: "02022" },
  { id: "yoga", group: "Mind & body", label: "Yoga, general", met: 2.3, code: "02175" },
  { id: "yoga-power", group: "Mind & body", label: "Power yoga", met: 4.0, code: "02160" },
  { id: "surya-namaskar", group: "Mind & body", label: "Yoga, Surya Namaskar (sun salutations)", met: 3.5, code: "02180" },
  { id: "pilates", group: "Mind & body", label: "Pilates, general", met: 2.8, code: "02105" },
  { id: "swim-slow", group: "Swimming", label: "Swimming laps, freestyle, slow", met: 5.8, code: "18240" },
  { id: "swim-fast", group: "Swimming", label: "Swimming laps, freestyle, fast", met: 9.8, code: "18230" },
  { id: "swim-leisure", group: "Swimming", label: "Swimming, leisurely", met: 6.0, code: "18310" },
  { id: "water-aerobics", group: "Swimming", label: "Water aerobics", met: 5.5, code: "18355" },
  { id: "basketball", group: "Sports", label: "Basketball, general", met: 7.5, code: "15055" },
  { id: "soccer", group: "Sports", label: "Soccer (football), casual", met: 7.0, code: "15610" },
  { id: "tennis", group: "Sports", label: "Tennis, moderate effort", met: 6.8, code: "15675" },
  { id: "badminton", group: "Sports", label: "Badminton, social", met: 5.5, code: "15030" },
  { id: "cricket", group: "Sports", label: "Cricket", met: 4.8, code: "15150" },
  { id: "dance", group: "Everyday", label: "Dancing, contemporary, general", met: 3.8, code: "03070" },
  { id: "vacuum", group: "Everyday", label: "Vacuuming", met: 3.0, code: "05043" },
];
